TASK 1 (Creating Arrays)

In [103]:
import numpy as np
import time

In [104]:
ar_1d=np.arange(1,11)

In [105]:
ar_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
ar_2d=np.arange(1,10).reshape(3,3)
ar_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
ar_3d=np.random.rand(3,5,3)

In [108]:
ar_3d

array([[[0.39217296, 0.04115659, 0.92330057],
        [0.40623497, 0.94428218, 0.72272449],
        [0.91831995, 0.82326754, 0.6468967 ],
        [0.06793902, 0.83881577, 0.6928224 ],
        [0.95799151, 0.14222247, 0.08777354]],

       [[0.51887998, 0.35993237, 0.96027368],
        [0.70377222, 0.44599407, 0.19220875],
        [0.44288141, 0.46628642, 0.00914256],
        [0.25721541, 0.2453717 , 0.38102144],
        [0.42403833, 0.26753056, 0.11264625]],

       [[0.13867957, 0.68820216, 0.95588973],
        [0.34485436, 0.14278639, 0.2600578 ],
        [0.15217505, 0.19473966, 0.66216051],
        [0.38492733, 0.25045429, 0.58115791],
        [0.89782395, 0.02442901, 0.59671877]]])

In [109]:
np.shape(ar_1d)


(10,)

In [110]:
np.shape(ar_2d)

(3, 3)

In [111]:
np.shape(ar_3d)

(3, 5, 3)

In [112]:
np.size(ar_3d)

45

In [113]:
np.size(ar_1d)

10

In [114]:
np.size(ar_2d)

9

In [115]:
ar_1d.dtype

dtype('int64')

In [116]:
ar_2d.dtype

dtype('int64')

In [117]:
ar_3d.dtype

dtype('float64')

TASK 2 (Array Indexing and Slicing)

In [118]:
data=[10,20,30,40,50,60,70,80,90]
arr=np.array(data)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [119]:
arr[0:3]

array([10, 20, 30])

In [120]:
arr[0::2]

array([10, 30, 50, 70, 90])

In [121]:
arr[-1::-1]

array([90, 80, 70, 60, 50, 40, 30, 20, 10])

TASK 3 (Mathematical Operation)

In [122]:
A=np.random.randint(1,20,size=5)
B=np.random.randint(1,20,size=5)
A,B

(array([17,  5,  5, 14,  8], dtype=int32),
 array([ 3, 12,  3,  8, 18], dtype=int32))

In [123]:
add=A+B
add

array([20, 17,  8, 22, 26], dtype=int32)

In [124]:
sub=A-B
sub

array([ 14,  -7,   2,   6, -10], dtype=int32)

In [125]:
mul=A*B
mul

array([ 51,  60,  15, 112, 144], dtype=int32)

In [126]:
div=A/B
div

array([5.66666667, 0.41666667, 1.66666667, 1.75      , 0.44444444])

In [127]:
dot_pro=A*B
dot_pro

array([ 51,  60,  15, 112, 144], dtype=int32)

In [128]:
A.mean()

np.float64(9.8)

In [129]:
A.std()

np.float64(4.874423042781577)

In [130]:
A.var()

np.float64(23.76)

In [131]:
np.median(A)

np.float64(8.0)

In [132]:
B.min(),B.max()

(np.int32(3), np.int32(18))

TASK 4 (Reshaping and Transposing)

In [133]:
arr=np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [134]:
arr_2D=arr.reshape(4,3)
arr_2D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [135]:
arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [136]:
arr_2D.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [137]:
np.shape(arr_2D.T)

(3, 4)

TASK 5 (Boolean Masking and Filtering)

In [138]:
arr=np.random.randint(10,50,size=15)
arr

array([44, 47, 24, 16, 11, 45, 23, 13, 45, 36, 32, 21, 40, 49, 12],
      dtype=int32)

In [139]:
arr[arr>25]

array([44, 47, 45, 45, 36, 32, 40, 49], dtype=int32)

In [140]:
arr[arr<30]=0
arr

array([44, 47,  0,  0,  0, 45,  0,  0, 45, 36, 32,  0, 40, 49,  0],
      dtype=int32)

In [141]:
count=arr[arr%5==0]
len(count)

10

TASK 6 (Working with built in Functions)

In [142]:
ar=np.linspace(0,1,10)
ar

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [143]:
ar=np.identity(4)
ar

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [144]:
ar_ran=np.random.randint(1,100,size=20)
ar_ran

array([27, 65, 77,  9, 66, 48, 29, 54, 54, 25,  4, 32, 26, 51, 86, 58, 99,
       79, 88, 54], dtype=int32)

In [145]:
ar_ran.sort()
ar_ran

array([ 4,  9, 25, 26, 27, 29, 32, 48, 51, 54, 54, 54, 58, 65, 66, 77, 79,
       86, 88, 99], dtype=int32)

In [146]:
ar_ran[len(ar_ran)-5:len(ar_ran)]

array([77, 79, 86, 88, 99], dtype=int32)

TASK 7 (Generic)

In [147]:
np.random.seed(0)
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

In [148]:
start_time = time.time()
C = np.dot(A, B) 

In [149]:
try:
    det_C = np.linalg.det(C)
    print(f"Determinant of the result matrix: {det_C:.4e}")
except np.linalg.LinAlgError:
    print("Determinant could not be calculated.")

Determinant of the result matrix: 6.0159e+50


In [150]:
try:
    inv_C = np.linalg.inv(C)
    print("Inverse matrix calculated successfully.")
except np.linalg.LinAlgError:
    print("Matrix is singular and cannot be inverted.")

Inverse matrix calculated successfully.


In [154]:
end_time = time.time()
time_taken = end_time - start_time
time_taken

48.61456561088562